logging:
  level:
    root: WARN
    me:
      marcelberger: INFO
spring:
  datasource:
    driverClassName: 'org.mariadb.jdbc.Driver'
    url: 'jdbc:mariadb://localhost:3306/weatherapp'
    username: 'admin'
    password: 'admin'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        order_by:
          default_null_ordering: last
  mail:
    host: 'localhost'
    port: 1025
    username: 'test@mail'
    password: ''
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

weatherapp: