logging:
  level:
    root: WARN
    me:
      marcelberger: INFO
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
spring:
  datasource:
    driverClassName: 'org.mariadb.jdbc.Driver'
    url: 'jdbc:mariadb://localhost:3306/weatherapp'
    username: 'admin'
    password: 'admin'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        order_by:
          default_null_ordering: last
  mail:
    host: 'localhost'
    port: 1025
    username: 'test@mail'
    password: ''
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

weatherapp:
  usage:
    requestsPerMinute: 2
  media:
    directory: S:/weatherapp/media
  station:
    media:
      latestKey: LATEST
      baseUrl: "http://localhost:8080/station/media?station={station}&name={name}"
      directory: ${weatherapp.media.directory}/station
  openAI:
    api:
      host: https://api.openai.com
      path: /v1/chat/completions
      key: 123
      timeoutSeconds: 30
    model: gpt-3.5-turbo
    messageTemplate:
      system: 'You are a weather app assistant. Time is {time}.'
      user: '{message}. Do not answer if context of this message is not about weather.'
    functions:
      filePattern: classpath:openai/function_{name}.json
      available: weather_record, weather_time
